name: lstm
module:
  _target_: poetry_generator.models.PoetryLightningModel
  model_type: lstm
  embedding_dim: 512
  hidden_dim: 512
  n_layers: 3
  learning_rate: 0.001
  weight_decay: 0.0
  label_smoothing: 0.05
  embedding_dropout: 0.2
  rnn_dropout: 0.3
  output_dropout: 0.2
  layer_norm: true
  tie_weights: true
  unk_token: ${data.unk_token}
samples:
  prompts:
    - "冬"
    - "中国"
  max_len: 96
  temperature: 0.9
