name: rnn
module:
  _target_: poetry_generator.models.PoetryLightningModel
  model_type: rnn
  embedding_dim: 256
  hidden_dim: 512
  n_layers: 3
  learning_rate: 0.001
  weight_decay: 0.0
  embedding_dropout: 0.1
  rnn_dropout: 0.2
  output_dropout: 0.1
  layer_norm: true
  tie_weights: true
samples:
  prompts:
    - "春江花月夜"
    - "人工智能"
  max_len: 96
  temperature: 0.9
