- _target_: poetry_generator.callbacks.SaveVocabCallback
  output_path: ${hydra:run.dir}/vocab.json
- _target_: poetry_generator.callbacks.LogGenerationSamplesCallback
  prompts: ${model.samples.prompts}
  max_len: ${model.samples.max_len}
  temperature: ${model.samples.temperature}
- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${hydra:run.dir}/checkpoints
  filename: best-model
  monitor: val/loss
  mode: min
  save_top_k: 1
  save_last: true
- _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: epoch
  log_momentum: False
