max_epochs: 50
accelerator: auto
devices: auto
strategy: auto

precision: bf16-mixed
sync_batchnorm: True
benchmark: True
accumulate_grad_batches: 1
gradient_clip_val: 1.0

num_sanity_val_steps: 0
val_check_interval: 1.0
log_every_n_steps: 50
