max_epochs: 20
accelerator: auto
devices: [2, 3]
strategy: auto

precision: 16-mixed
sync_batchnorm: True
benchmark: True
accumulate_grad_batches: 1
gradient_clip_val: 1.0

val_check_interval: 1.0
log_every_n_steps: 50
